blog/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'blog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'blog/', include('blog_app.urls', namespace="blog")),
)

blog_app/urls.py
from django.conf.urls import patterns, url
from blog_app import views

urlpatterns = patterns('',

#     url(r'^$', views.IdexView.as_view(), name='index'),
#     url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
#     url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^$', views.index, name='index'),
    url(r'^post/$', views.all_posts, name='post'), 
    url(r'^post/(?P<post_id>\d+)/$', views.detail, name='detail'),
    url(r'^category/(?P<cat_id>\d+)/$', views.category, name='category'),
    url(r'^about/$', views.about, name='about'),
    url(r'^login/$', views.login, name='login'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^password_restore/$', views.password_restore, name='password_restore'),
    url(r'^create_account/$', views.create_account, name='create_account'),
    
    
    
    
)

blog_app/models.py
from django.db import models
from django.utils import timezone, datetime_safe
from django.contrib.auth.models import User
from datetime import datetime


class Category(models.Model):
    name = models.CharField(max_length=60, blank=True, null=True)
    def __unicode__(self):
        return self.name
    
    
class Post(models.Model):
    fk_user = models.ForeignKey(User)
    fk_cat = models.ForeignKey(Category)
    title = models.CharField(max_length=60)
    body = models.TextField(max_length=500)
    pub_date = models.DateTimeField('date published', default=timezone.now())
    
    def __unicode__(self):
        return self.title
    

class Comment(models.Model):
    fk_user = models.ForeignKey(User)
    fk_post = models.ForeignKey(Post)
    text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __unicode__(self):
        return self.pub_date


class Address(models.Model):
    country = models.CharField(max_length=20)
    state = models.CharField(max_length=20)
    city = models.CharField(max_length=20)
    pcode = models.CharField(max_length=10)
    street = models.CharField(max_length=60)
    
    
class Person(models.Model):
    fk_user = models.ForeignKey(User)
    fk_addr = models.ForeignKey(Address, blank=True)
    pic = models.BinaryField()
    name = models.CharField(max_length=20)
    surname = models.CharField(max_length=40)
    dob = models.DateField()
    extra_info = models.TextField(max_length=500)
    age = models.IntegerField(blank=True)
    


    
    
    

blog_app/forms.py
from django import forms

class CreateAccountForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField()
    email_confirm = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())
    password_confirm = forms.CharField(widget=forms.PasswordInput())
#     TODO
#     def send_email(self):
#         # send email using the self.cleaned_data dictionary
#         pass


class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    subject = forms.CharField()
    content = forms.CharField(widget=forms.Textarea)
#     TODO
#     def send_email(self):
#         # send email using the self.cleaned_data dictionary
#         pass


# class LoginForm(form.Form):
#     username = forms.CharField()
#     password = forms.CharField(widget=forms.PasswordInput())
    
    

blog_app/views.py
from django.utils import timezone
from django.http.response import HttpResponseRedirect
# Shortcuts
from django.shortcuts import render, render_to_response, get_object_or_404
# Core
from django.core.urlresolvers import reverse
from django.core.context_processors import request
from django.core.context_processors import csrf
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Auth
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as auth_login
# Models
from blog_app.models import Post, Comment, Category
# Forms
from blog_app.forms import CreateAccountForm, ContactForm
# Loggin
import logging
# from django.views import generic



logger = logging.getLogger(__name__)


def index(request):
    vals = {}
    vals['latest_post_list'] = Post.objects.order_by('pub_date')[:5]
    vals['categories_list'] = Category.objects.order_by('name')
    return render(request, 'blog_app/index.html', vals)


def all_posts(request):
    post_list = Post.objects.order_by('pub_date')
    paginator = Paginator(post_list, 6)
    page = request.GET.get('page')
    
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    
    vals = {}
    vals['latest_post_list'] = posts
    vals['categories_list'] = Category.objects.order_by('name')
    return render(request, 'blog_app/index.html', vals)
    
    
def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    # if write a comment
    if request.method=='POST':
        if request.POST.get("text"):
            text = request.POST.get("text")
            user = request.user
            c = Comment.objects.create(fk_post = post, text = text, pub_date = timezone.now(), fk_user = user)
            c.save()
            return HttpResponseRedirect('.')
    # load all comments
    comments = Comment.objects.filter(
            fk_post=post_id
        ).order_by('pub_date')
    
    return render(request,'blog_app/detail.html',{'post':post, 'comment_list':comments})


def login(request):
    url = 'blog_app/login.html'
    vals = {}
    vals.update(csrf(request))
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['pass']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                auth_login(request, user)
                return HttpResponseRedirect('/blog')
            else:
                vals['error_msg'] ='Usuario inactivo!'
                logger.error("Inactive user trying to login")
        else:
            vals['error_msg'] = 'Usuario o contrasenya incorrecta!'
            logger.error("User %s Login attempt failed" % (username and username or 'Blank'))
    return render(request, url, vals)
    
    
def logout_view(request):
    logout(request)
    return index(request)
    

def about(request):
    # TODO
    return render(request,'blog_app/about.html',{})
    
def password_restore(request):
    # TODO
    return render(request, 'blog_app/password_restore.html', {})


def create_account(request):
    if request.method == 'POST':
        form = CreateAccountForm(request.POST)
        if form.is_valid():
            return HttpResponseRedirect('/blog')
    else:
        form = CreateAccountForm()
    return render(request, 'blog_app/create_account.html', {'form':form})


def category(request, cat_id):
    vals = {}
    vals['categories_list'] = Category.objects.order_by('name')
    vals['latest_post_list'] = Post.objects.filter(
        fk_cat=cat_id
    ).order_by('pub_date')
    return render(request, 'blog_app/index.html', vals)


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            return HttpResponseRedirect('/blog')
    else:
        form = ContactForm()
    return render(request, 'blog_app/contact.html', {'form':form})

blog_app/templates/blog_app/about.html
{% extends "blog_app/base.html" %}
{% block content %}
	
<p> text text text text text text text text text text text text text text text text text text 
text text text text text text text text text text text text text text text text text text 
text text text text text text text text text text text text text text text text text text 
text text text text text text text text text text text text text text text text text text 
text text text text text text text text text text text text text text text text text text text text text 
text text text </p>
{% endblock content %}
{% block cat_index %}{% endblock cat_index %}

blog_app/templates/blog_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'blog_app/style.css' %}" />
</head>

<body>
	<div class="wrapper">
	    <div class="nav">
	        {% block navbar %}
	        	{% include "blog_app/nav.html" %}
	        {% endblock navbar %}
	    </div>
	
	     <div class="content">
	        {% block content %}{% endblock content %}
	    </div>
	    
	    <div class="sidebar">
	    	{% block cat_index %}
	    		{% include "blog_app/cat_index.html" %}
	    	{% endblock cat_index %}
	    </div>
	    
	    <div class="footer">
	    	{% block footer %}
	    		{% include "blog_app/footer.html" %}
	    	{% endblock footer %}
	    </div>
    </div>
</body>
</html>

blog_app/templates/blog_app/cat_index.html
{% block cat_index %}

	{% if categories_list %}
	    <ul>
	    {% for cat in categories_list %}
	        <li><a href="{% url 'blog:category' cat.id %}">{{ cat }}</a></li>
	    {% endfor %}
	    </ul>
	{% else %}
	    <p>No Categories available.</p>
	{% endif %}

{% endblock cat_index %}

blog_app/templates/blog_app/contact.html
{% extends "blog_app/base.html" %}
{% block content %}

    <h3>Contact Form</h3>
	<form action="{% url 'blog:contact' %}" method="post">
	    {% csrf_token %}
	    <table>
	    	{{ form.as_table }}
	    </table>
	    <input type="submit" value="Submit" />
	</form>
    
{% endblock content %}

{% block cat_index %}{% endblock cat_index %}

blog_app/templates/blog_app/create_account.html
{% extends "blog_app/base.html" %}
{% block content %}

    {% if form.errors %}

    {% endif %}
    <h3>New account</h3>
	<form action="{% url 'blog:create_account' %}" method="post">
	    {% csrf_token %}
	    {{ form }}
	    <input type="submit" value="Submit" />
	</form>
    
{% endblock content %}

{% block cat_index %}{% endblock cat_index %}

blog_app/templates/blog_app/detail.html
{% extends "blog_app/base.html" %}
{% block content %}

	<!-- POST -->
	
	<h2>{{ post }}</h2>
	<h3>{{ post.pub_date }} by {{ post.fk_user }}</h3>
	<p>{{ post.body }}</p>
	<p>Category <a href="{% url 'blog:category' post.fk_cat.id %}">{{ post.fk_cat }}</a></p>
	
	<!-- WRITE COMMENT -->
	
	{% if user.is_authenticated %}
		
		<form action="{% url 'blog:detail' post.id %}" method="POST">
			{% csrf_token %}
			<input type="text" name="text"/>
			<input type="submit" value="Write a comment"/>
			<input type="hidden" name="user_id" value="{{ user.id }}"/>
		</form>
	{% else %}
		<p>You need to <a href="{% url 'blog:login' %}">Login</a> to write a comment</p>
	{% endif %}
	
	<!-- COMMENTS -->
	
	<h3>Comments</h3>
	{% if comment_list %}
	    <ul>
	    {% for comment in comment_list %}
	        <li>
	        	<p>{{ comment.pub_date }} by {{ post.fk_user }} </p>
	        	<p>{{ comment.text }}</p>
	        </li>
	    {% endfor %}
	    </ul>
	{% else %}
	    <p>This Post has no comments.</p>
	{% endif %}

{% endblock content %}

blog_app/templates/blog_app/footer.html
<ul>
	<li><a href="">Facebook</a></li>
	<li><a href="">Twitter</a></li>
	<li><a href="">G+</a></li>
	<li><a href="">Youtube</a></li>
	<li><a href="">RSS</a></li>
</ul>

blog_app/templates/blog_app/index.html
{% extends "blog_app/base.html" %}
{% block content %}
	{% if latest_post_list %}
	    <ul>
	    {% for post in latest_post_list %}
	        <li><a href="{% url 'blog:detail' post.id %}">{{ post.title }} - {{ post.pub_date }}</a></li>
	    {% endfor %}
	    </ul>
	{% else %}
	    <p>No Post are available.</p>
	{% endif %}
	
	<div class="pagination">
		<span>
			{% if latest_post_list.has_previous %}
				<a href="?page={{ latest_post_list.previous_page_number }}">previous</a>
			{% endif %}
			{% if latest_post_list.has_previous or latest_post_list.has_next %}
		    <span class="current">
		        Page {{ latest_post_list.number }} of {{ latest_post_list.paginator.num_pages }}.
		    </span>
		    {% endif %}
		    {% if latest_post_list.has_next %}
		    	<a href="?page={{ latest_post_list.next_page_number }}">next</a>
		    {% endif %}
		</span>
	</div>
		

{% endblock content %}

blog_app/templates/blog_app/login.html
{% extends "blog_app/base.html" %}
{% block content %}
	
	<h3>Login</h3>
	
	{% if error_msg %}
		<p>{{error_msg}}</p>
	{% endif %}
	
		<form method="post" action="{% url 'blog:login' %}">
		{% csrf_token %}
		<table>
		<tr>
		    <td>Username</td>
		    <td><input type="text" name="username"></td>
		</tr>
		<tr>
		    <td>Password</td>
		    <td><input type="password" name="pass"></td>
		</tr>
		</table>
		
		<input type="submit" value="login" />
		</form>
		
		<a href="{% url 'blog:password_restore' %}">Forgot your password?</a>
		</br>
		<a href="{% url 'blog:create_account' %}">Create a new account</a>

{% endblock content %}
{% block cat_index %}{% endblock cat_index %}

blog_app/templates/blog_app/nav.html
<ul>
	<li><a href="{% url 'blog:index' %}">Home</a></li>
	<li><a href="{% url 'blog:post' %}">All Posts</a></li>
	<li><a href="{% url 'blog:about' %}">About</a></li>
	<li><a href="{% url 'blog:contact' %}">Contact</a></li>
	
	{% if user.is_authenticated %}
		<li>
			Hello, {{user.username}}
			<a href="{% url 'blog:logout' %}">Logout</a>
		</li>
	{% else %}
		<li>
			<a href="{% url 'blog:login' %}">Login</a> / <a href="{% url 'blog:create_account' %}">Sing up</a>
		</li>
	{% endif %}
	
</ul>

blog_app/templates/blog_app/password_restore.html
{% extends "blog_app/base.html" %}
{% block content %}
    
    <h3>Password restore</h3>
    <p>TODO: Password restore form</p>
    
{% endblock content %}

{% block cat_index %}{% endblock cat_index %}

blog_app/templates/blog_app/sidebar.html
<p>Just a sidebar</p>